# This file was generated by the `rails generate rspec:install` command.
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups

  # Tag examples with `:focus` (or use fit/fdescribe/fcontext) to run only those.
  # When nothing is tagged, all examples run.
  config.filter_run_when_matching :focus

  # Persist state between runs to support --only-failures and --next-failure.
  config.example_status_persistence_file_path = "tmp/rspec_examples.txt"

  # Recommended: only the non-monkey-patched syntax.
  config.disable_monkey_patching!

  # Use the documentation formatter (clear, per-example output) when running a single file.
  if config.files_to_run.one?
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and groups at the end of the run.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies.
  config.order = :random
  Kernel.srand config.seed
end
